include_recipe "platform_yum"
include_recipe "platform_java"
#include_recipe "infra_duo"
include_recipe "tools_sdlc::proxy"
include_recipe "tools_sdlc::tomcat"
#include_recipe "tools_sdlc::httpd"
include_recipe "tools_sdlc::newrelic"
include_recipe "platform_chef-splunk"
#include_recipe "tools_sdlc::deploy" unless node['dczone'][0,5] == "prfqy"
include_recipe "tools_sdlc::deploy"
include_recipe "tools_sdlc::permissions"
