name             'mysdlc'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mysdlc'
long_description 'Installs/Configures mysdlc'
version          '0.1.0'
